Repository AICoE/workshop-coding-best-practices, pull requests merged in 2019-10, with the labels that each got.

#25 py linting and coala fixes
  model.py
  myproject/module.py
  tests/test_module.py
Labels: approved, human_intervention_required, size/M

#24 Added Kebechet support
  .thoth.yaml
Labels: approved, size/S

#27 Automatic update of dependency hypothesis from 4.23.9 to 4.40.0
  Pipfile.lock
Labels: bot

#18 Automatic update of dependency numpy from 1.16.4 to 1.17.2
  Pipfile.lock
Labels: bot

#19 Automatic update of dependency matplotlib from 3.1.0 to 3.1.1
  Pipfile.lock
Labels: bot

#20 Automatic update of dependency pandas from 0.24.2 to 0.25.1
  Pipfile.lock
Labels: bot

#21 Automatic update of dependency pytest-cov from 2.7.1 to 2.8.1
  Pipfile.lock
Labels: bot

#29 Automatic update of dependency hypothesis from 4.40.0 to 4.40.1
  Pipfile.lock
Labels: bot

#30 Automatic update of dependency hypothesis from 4.40.1 to 4.40.2
  Pipfile.lock
Labels: bot

#32 Automatic update of dependency hypothesis from 4.41.0 to 4.41.1
  Pipfile.lock
Labels: bot

#34 Automatic update of dependency numpy from 1.17.2 to 1.17.3
  Pipfile.lock
Labels: bot

#33 Automatic update of dependency hypothesis from 4.41.1 to 4.41.2
  Pipfile.lock
Labels: bot

#35 Automatic update of dependency pandas from 0.25.1 to 0.25.2
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase

#36 Automatic update of dependency hypothesis from 4.41.2 to 4.41.3
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase

#37 Automatic update of dependency pytest from 5.2.1 to 5.2.2
  Pipfile.lock
Labels: bot

#38 Automatic update of dependency hypothesis from 4.41.3 to 4.42.0
  Pipfile.lock
Labels: bot

#39 Automatic update of dependency hypothesis from 4.42.0 to 4.42.2
  Pipfile.lock
Labels: bot

#40 Automatic update of dependency hypothesis from 4.42.2 to 4.42.3
  Pipfile.lock
Labels: bot
