Repository AICoE/workshop-coding-best-practices, pull requests merged in 2020-02, with the labels that each got.

#129 Automatic update of dependency hypothesis from 5.4.0 to 5.4.1
  Pipfile.lock
Labels: bot, size/XS

#130 Automatic update of dependency matplotlib from 3.1.2 to 3.1.3
  Pipfile.lock
Labels: bot, size/S

#131 Automatic update of dependency pandas from 1.0.0 to 1.0.1
  Pipfile.lock
Labels: bot, size/M

#132 Automatic update of dependency hypothesis from 5.4.1 to 5.4.2
  Pipfile.lock
Labels: bot, size/XS

#134 Automatic update of dependency hypothesis from 5.4.2 to 5.5.1
  Pipfile.lock
Labels: bot, size/XS

#135 Update .thoth.yaml
  .thoth.yaml
Labels: approved, size/XS

#136 Automatic update of dependency hypothesis from 5.5.1 to 5.5.2
  Pipfile.lock
Labels: bot, size/S

#137 Automatic update of dependency hypothesis from 5.5.2 to 5.5.3
  Pipfile.lock
Labels: bot, size/XS

#138 Automatic update of dependency hypothesis from 5.5.3 to 5.5.4
  Pipfile.lock
Labels: bot, size/XS

#139 Automatic update of dependency hypothesis from 5.5.4 to 5.5.5
  Pipfile.lock
Labels: bot, size/M

#140 Automatic update of dependency hypothesis from 5.5.5 to 5.6.0
  Pipfile.lock
Labels: bot, size/XS
